Fix linter issues - prettier (#403)

diff --git a/docs/.gitlab-ci.yml b/docs/.gitlab-ci.yml
--- a/docs/.gitlab-ci.yml
+++ b/docs/.gitlab-ci.yml
@@ -145,10 +145,10 @@ check_accessibility_vagrant_cloud:
     - packer-templates
   script:
     - for NAME in ubuntu-{18.10,18.04}-desktop-amd64 ubuntu-{18.04,16.04,14.04}-server-amd64 my_ubuntu-{18.04,16.04}-server-amd64 my_centos-7-x86_64 my_windows-10-enterprise-x64-eval windows-{server-{{2016,2012_r2}-standard,2019-datacenter},10-enterprise}-x64-eval; do
-        for VAGRANT_PROVIDER in virtualbox libvirt; do
-          CURRENT_VERSION=$(curl -s https://app.vagrantup.com/api/v1/box/peru/$NAME | jq -r ".current_version.version") ;
-          URL="https://app.vagrantup.com/peru/boxes/$NAME/versions/$CURRENT_VERSION/providers/$VAGRANT_PROVIDER.box" ;
-          echo "*** $URL" ;
-          curl -L --fail --silent --head --output /dev/null "$URL" || ( echo "* Failed... ^^^" && exit 1 )
-        done
+      for VAGRANT_PROVIDER in virtualbox libvirt; do
+      CURRENT_VERSION=$(curl -s https://app.vagrantup.com/api/v1/box/peru/$NAME | jq -r ".current_version.version") ;
+      URL="https://app.vagrantup.com/peru/boxes/$NAME/versions/$CURRENT_VERSION/providers/$VAGRANT_PROVIDER.box" ;
+      echo "*** $URL" ;
+      curl -L --fail --silent --head --output /dev/null "$URL" || ( echo "* Failed... ^^^" && exit 1 )
+      done
       done
